language: generic
dist: bionic
sudo: false
env:
  global:
  - HELM_VERSION="v3.5.0"
  - secure: L6DH9/gZFYtcYm2NFNB0LXI9WzA6yrsjZNBGha/YtKjiiRd44+LiwkeP4tWp9Ytc0NA+hTSgmZ4pGbu7LbiD3HxosnGfGYe6vIfO3LkpMWomvUvcHovv1xFp98n09jA/XyJWS9IngV/1VU/o8fQELjZYjJNC0QlYW3x20AuhKqGXv9g8Hjcmng9/EgfvDzJdxUg9+WoXpaQJ0kc5bmbIy30MDkp4edYRCzGXsK01AZjYz/YLCeQo6AX7NQGcH1L/bf1HuMsVs5ojSxcsXFQkb6hOzK8KRnorgI0snYrBDH92NAWrfvgZ1rkReLnikyZ9wp6JcHhbmnV8mUUuPOoCoPy3MZJMiLUHTO2mHCM28VCvD3JbOiUbbJV0VU/XEi2UBkZEsIAoGr1LLzgYtJ720M4UDjxDRQo/AvzJc+dU9SljjfnojmaunXpxXBP1WnCZyhjc2yTzeaDLP4nNYvoQnrVjb9He+fyDqW0t1tWFGJmfKR1gL/yjKSXqj8AaVeSJpaJKP6kuuQ7HAaFrmxIp3Alt0f6IZ9FVMXTmCu3HtSIC4s9v0Er0Hn3bx+3d2bsCVbDLqncIjfZt1yAqH8sUfWn7D4p5fTNy7ME0gIqxUZgryEch29I1ak31PPaWqDrOvMQPPgqMY4P0BC787SmRksNylJZzsXNJMC5Api+VkJc=
install:
- sudo apt-get update
- sudo apt-get install -y yamllint
- wget https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
- tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
- chmod +x /tmp/helm
script:
- |
  for chart in $(find . -name 'Chart.yaml'); do
    echo "=========== Begin $(dirname ${chart}) ==========="

    set -x
    /tmp/helm dep build $(dirname ${chart})
    /tmp/helm lint $(dirname ${chart})
    template=$(/tmp/helm template $(dirname ${chart}))
    set +x

    # See if the output is valid yaml
    echo $template | yamllint -d relaxed /dev/stdin

    echo "=========== End $(dirname ${chart}) ==========="
  done
deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
