apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: {{ .Chart.Name }}
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          serviceAccountName: {{ template "ecr-cred-helper.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            env:
            - name: ACCOUNT
              value: "{{ .Values.ecr.account_id }}"
            - name: REGION
              value: "{{ .Values.ecr.region }}"
            resources: {}
            securityContext:
              capabilities: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: Default
          hostNetwork: true
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: 3
  suspend: false
