{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "ecr-cred-helper.roleName" . }}
  labels:
{{ include "ecr-cred-helper.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["delete"]
  resourceNames: ["us-east-1-ecr-registry"]
{{- end -}}
