dependencies:
  - name: mysql
    alias: development_mysql
    version: 1.3.1
    repository: https://charts.helm.sh/stable
    condition: development_mysql.enabled,global.development_mysql.enabled
  - name: elasticsearch
    alias: development_elasticsearch
    version: 7.3.2
    repository: https://helm.elastic.co
    condition: development_elasticsearch.enabled,global.development_elasticsearch.enabled
