---
app: 
    name: my-app
    image:
        tag: 133d963baf5daa915f47a2143c4d076a92302e99-newrelic
        repository: openedx/my-app
    role_arn: '' #arn:aws:iam::77777777:role/prod-my-app
    command: 'gunicorn --workers=2 --name my_app -c /edx/app/my_app/my_app/docker_gunicorn_configuration.py --log-file - --max-requests=1000 my_app.wsgi:application'
    secret_file_env_name: MY_APP_CFG
    secret_file_name: my_app.yml
    service_account_name: my-app
    extraEnvs: []
        # - name: MY_ENV
        #   value: myvalue
    migrations:
        name: my-app-migrations
        enabled: true
        database_migrate_user: migrate001
        migrate_db_user_env_name: DB_MIGRATION_USER
        migrate_db_pass_env_name: DB_MIGRATION_PASS

    autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 10
        targetCPUUtilizationPercentage: 50

    health_check: 
        endpoint: "/health"
        liveness_probe_initial_delay_seconds: 0
        readiness_probe_initial_delay_seconds: 0
        
    config: {} # Your yaml config goes here


workers: []
    # - name: my-app-worker
    #   command: celery -A my_app worker --loglevel info

newrelic:
    enabled: true
    app_name: prod-my-app
    log_level: info

collectstatic:
    enabled: false
    job_name: my-app-collectstatic
    s3_bucket: s3://prod-my-app-assets
    asset_write_role: arn:aws:iam::77777777:role/prod-my-app-assets-rw
    
vault:
    enabled: true
    use_tls: true
    vault_role: my-app
    vault_addr: https://vault.prod.edx.org
    secret_name: kv/my-app
    secret_version: 1

ingresses: []
    # - host: my-app.edx.org
    #   class: public

    # - host: my-app-internal.edx.org
    #   class: internal
    #   allow_django_admin: true

cronjobs: []
    # - name: my-app-retire-old-licenses
    #   schedule: 0 13 * * *
    #   command: /edx/app/my_app/manage.py retire_old_licenses
