dependencies:
  - name: elasticsearch
    version: 7.3.2
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled,global.elasticsearch.enabled
  - name: mysql
    version: 1.3.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mysql.enabled,global.mysql.enabled
