{{ if .Values.migrations.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.migrations.migrationContainerName }}
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 0
  template:
    name: {{ .Values.migrations.migrationContainerName }}
    spec: 
      volumes:
        - name: {{ include "notes.applicationSecretName" . }}
          secret:
            secretName: {{ include "notes.applicationSecretName" . }}
      restartPolicy: Never
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.31.0
          command: ['sh', '-c', 'until nslookup {{ .Values.app.config.DATABASES.default.HOST }}; do echo waiting for {{ .Values.app.config.DATABASES.default.HOST }}; sleep 2; done;']
      containers:
        - name: {{ .Values.migrations.migrationContainerName }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          command: ["python3", "manage.py", "migrate"]
          restartPolicy: Never
          volumeMounts:
            - mountPath: "/edx/etc"
              name: {{ include "notes.applicationSecretName" . }}
              readOnly: true
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
{{- end }} # Values.migrations.enabled
