# Check for required values by rendering them
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes.applicationSecretName" . }}
type: Opaque
stringData:
# Check for required values but dont render them.  Just dumb render the contents of Values.app.config if all required secrets are present
  edx_notes_api.yml: |-
{{ toYaml .Values.app.config | indent 4 }}
