# Check for required values by rendering them
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes.applicationSecretName" . }}
type: Opaque
stringData:
# Check for required values but dont render them.  Just dumb render the contents of Values.app.config if all required secrets are present
  edx_notes_api.yml: |-
{{ toYaml .Values.app.config | indent 4 }}
  required: |-
    variables:
{{- required "A valid .Values.app.config.SECRET_KEY entry required!" .Values.app.config.SECRET_KEY  | indent 6 }}
{{- required "A valid .Values.app.config.DATABASES.default.PASSWORD entry required!" .Values.app.config.DATABASES.default.PASSWORD   | indent 6 }}
{{- required "A valid .Values.app.config.CLIENT_ID entry required!" .Values.app.config.CLIENT_ID   | indent 6 }}
{{- required "A valid .Values.app.config.CLIENT_SECRET entry required!" .Values.app.config.CLIENT_SECRET   | indent 6 }}
