{{- range $index, $ingress := .Values.ingresses }}
{{- with $ }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ $ingress.issuer }}
    kubernetes.io/ingress.class: {{ $ingress.class }}
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  {{ if $ingress.external_dns }}
    kubernetes.io/external-dns: "true"
  {{ end }}
  {{ if $ingress.external_dns_cloudflare }}
    kubernetes.io/external-dns-cloudflare: "true"
  {{ end }}
  {{ if $ingress.allow_django_admin }}
  {{ else}}
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      server_tokens off;
      location /admin {
        deny all;
        return 403;
      }
  {{ end }}
  labels:
    app.kubernetes.io/instance: {{ $.Values.app.name }}
    app.kubernetes.io/name: {{ $.Values.app.name }}
  name: {{ $.Values.app.name }}-{{ $.Values.app.name }}-{{ $index }}
spec:
  ingressClassName: {{ $ingress.class }}
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $.Values.app.name }}
              port:
                name: http
  tls:
  - hosts:
    - {{ $ingress.host }}
    secretName: {{ $.Values.app.name }}-tls-{{ $index }}
{{- end }}
{{- end }}
