{{- range $index, $ingress := .Values.ingresses }}
{{- with $ }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ $ingress.issuer }}
  {{- if $ingress.class }}
    kubernetes.io/ingress.class: {{ $ingress.class }}
  {{- end }}
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  {{- if $ingress.external_dns }}
    kubernetes.io/external-dns: "true"
  {{- end }}
  {{- if $ingress.external_dns_cloudflare }}
    kubernetes.io/external-dns-cloudflare: "true"
  {{- end }}
  {{- if $ingress.allow_django_admin }}
  {{- else }}
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      server_tokens off;
      location /admin {
        deny all;
        return 403;
      }
  {{- end }}
  labels:
    app.kubernetes.io/instance: {{ $.Values.app.name }}
    app.kubernetes.io/name: {{ $.Values.app.name }}
{{- /*
Append truncated sha256 of hostname in case we have mutliple ingresses of the same className
Comment is above if because putting it below breaks helm templating
*/ -}}
{{- if $ingress.className }}
  name: {{ $.Values.app.name }}-{{ $ingress.className }}-{{ $ingress.host | sha256sum | trunc 5 }}
{{- else }}
  name: {{ $.Values.app.name }}-{{ $.Values.app.name }}-{{ $index }}
{{- end }}
spec:
  {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className }}
  {{- end }}
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $.Values.app.name }}
              port:
                name: http
  tls:
  - hosts:
    - {{ $ingress.host }}
  {{- if $ingress.extra_tls_hosts }}
  {{- range $ingress.extra_tls_hosts }}
    - {{ . }}
  {{- end }}
  {{- end }}
{{- /*
Append truncated sha256 of hostname in case we have mutliple ingresses of the same className
Comment is above if because putting it below breaks helm templating
*/ -}}
  {{- if $ingress.className }}
    secretName: {{ $.Values.app.name }}-tls-{{ $ingress.className }}-{{ $ingress.host | sha256sum | trunc 5 }}
  {{- else }}
    secretName: {{ $.Values.app.name }}-tls-{{ $index }}
  {{- end }}
{{- end }}
{{- end }}
