---
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: app-cm
apiVersion: v1
data:
  {{ if .Values.app.migrations.enabled }}
  DATABASE_MIGRATE_USER: {{ .Values.app.migrations.database_migrate_user }}
  {{ end }}
  NEW_RELIC_APP_NAME: {{ .Values.newrelic.app_name }}
  NEW_RELIC_LOG_LEVEL: {{ .Values.newrelic.log_level }}
  S3_ASSET_BUCKET: {{ .Values.collectstatic.s3_bucket }}
  VAULT_ADDR: {{ .Values.vault.vault_addr }}
  VAULT_ROLE: {{ .Values.vault.vault_role }}
  {{ .Values.app.secret_file_name }}: |
    ---
    {{"{{"}} with secret "{{ .Values.vault.secret_name }}?version={{ .Values.vault.secret_version }}" {{"}}"}}
    {{ .Values.app.config}}
    {{"{{"}} end {{"}}"}}
  migrate.env: |+
    #!/bin/bash
    {{"{{"}} with secret "{{ .Values.vault.secret_name }}?version={{ .Values.vault.secret_version }}" {{"}}"}}
    export DB_MIGRATION_PASS={{"{{"}} .Data.data.DB_MIGRATION_PASS {{"}}"}}
    {{"{{"}} end {{"}}"}}

  secret.env: |
    #!/bin/bash
    export NEW_RELIC_LICENSE_KEY={{"{{"}} with secret "{{ .Values.vault.secret_name }}?version={{ .Values.vault.secret_version }}" {{"}}"}}{{"{{"}} .Data.data.NEW_RELIC_LICENSE_KEY {{"}}"}}{{"{{"}} end {{"}}"}}
  
  vault.hcl: |
    "vault" = {
      "vault_agent_token_file" = "/vault-auth-secrets/secrets/.vault-token"
      "renew_token" = false
    }