{{- if and (eq .Values.secrets.source "kubernetes") (gt (len .Values.kubernetesSecrets) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
data: 
{{- range $key, $value := .data }}
  {{ $key }}: {{ printf "%s" $value | b64enc | quote }}
{{- end }}
{{- end }}
