name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Changes
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.EDX_DEPLOYMENT_GH_TOKEN }}
        run: bash .ci/deploy.sh
