name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Changes
        run: bash .travis/deploy.sh
